output: ./data/partition- .txt
files:
  - ./data/trigrams-0.txt
  - ./data/trigrams-1.txt
  - ./data/trigrams-2.txt
  - ./data/trigrams-3.txt
  - ./data/trigrams-4.txt
  - ./data/trigrams-5.txt
  - ./data/trigrams-6.txt
  - ./data/trigrams-7.txt
  - ./data/trigrams-8.txt
  - ./data/trigrams-9.txt
  - ./data/trigrams-10.txt
  - ./data/trigrams-11.txt
  - ./data/trigrams-12.txt
  - ./data/trigrams-13.txt
  - ./data/trigrams-14.txt
  - ./data/trigrams-15.txt
  - ./data/trigrams-16.txt
  - ./data/trigrams-17.txt
  - ./data/trigrams-18.txt
  - ./data/trigrams-19.txt
separators:
  - \%2CR
  - \%E1%
  - 0m%2
  - Baro
  - Hewa
  - OnJa
  - Toda
  - andd
  - bega
  - diff
  - grea
  - into
  - non-
  - onDe
  - roya
  - theA
  - them
  - tot